### ISSUE TITLE
Site got some overflow-x

### ISSUE THREAD

**Issue by bonniesimon** [bundit/kord-app#17]
As a result of setting a div to width : 100vw, there is a overflow in the landing component.

**Comment by bonniesimon** [comment]
I can help you with this, can you create a contributing.md which tells me on how to help you. That would be cool.

**Comment by bundit** [comment]
Nice catch! I'll look into creating a contributing guide.

Thanks for taking a look.

**Comment by bundit** [comment]
@bonniesimon 

Nice catch! I'll look into creating a contributing guide.
Thanks for taking a look.

**Comment by bonniesimon** [comment]
> 
> 
> @bonniesimon
> 
> Nice catch! I'll look into creating a contributing guide.
> Thanks for taking a look.

It'd be cool if I could contribute. Once you do the contributing guide, can I help?

**Comment by bundit** [comment]
#23 Fixed this issue
