### ISSUE TITLE
Connect with Spotify fails

### ISSUE THREAD

**Issue by SeriousM** [bundit/kord-app#18]
I use Firefox - latest version and Chrome - latest version.

When I joined Kord I selected Spotify which worked and I saw the interface.
Then I connected YT and Soundcloud.

> For soundcloud the profile url must be explicitly start with "soundcloud.com", not "https://soundcloud.com"

I didn't see any spotify playlists so I tried to refresh the spotify souce but got an error.
The network panel reveals that the request worked well so I guess kord can't process it.

I removed the spotify source and tried to add it again but got an error from spotify:

URL: `https://accounts.spotify.com/authorize?show_dialog=true&response_type=code&redirect_uri=https%3A%2F%2Fwww.kord.app%2Fauth%2Fspotify%2Flink%2Fcallback&scope=user-read-email%20user-read-private%20user-read-playback-state%20streaming%20user-modify-playback-state%20playlist-modify-public%20user-library-modify%20user-top-read%20playlist-read-collaborative%20user-read-currently-playing%20playlist-read-private%20user-follow-read%20user-read-recently-played%20playlist-modify-private%20user-library-read&client_id=4eed0f25c5e84aedb858c6ab99ce30f0`

`INVALID_CLIENT: Invalid redirect URI`

When login to kord with spotify the url is different: `https://accounts.spotify.com/en/authorize?show_dialog=true&response_type=code&redirect_uri=https:%2F%2Fwww.kord.app%2Fauth%2Fspotify%2Fcallback&scope=user-read-email%20user-read-private%20user-read-playback-state%20streaming%20user-modify-playback-state%20playlist-modify-public%20user-library-modify%20user-top-read%20playlist-read-collaborative%20user-read-currently-playing%20playlist-read-private%20user-follow-read%20user-read-recently-played%20playlist-modify-private%20user-library-read&client_id=4eed0f25c5e84aedb858c6ab99ce30f0`

I kord has a url encode problem when logged in in kord.

**Comment by ArunTeltia** [comment]
I connected to spotify first than when I try to connect to spotify I am getting an back to safety error in google authentication

**Comment by stopyellingatme** [comment]
I have the same issue as stated by @SeriousM.

Getting an Invalid Redirect URI.

**Comment by bundit** [comment]
@SeriousM Thank you for reporting this issue! Looking into it now

**Comment by bundit** [comment]
Commit d1665fc8ce61c4c153d4df2db100f4d21d1a2886 addresses the soundcloud url formatting to allow all forms of urls (http://soundcloud.com, https://www.soundcloud.com, soundcloud.com, ect)

Still looking into invalid redirect uri error

**Comment by bundit** [comment]
@SeriousM @stopyellingatme I believe I have resolved the "Invalid Redirect URI" issue. Could you confirm that you aren't getting that error anymore?

I will need to look further into why @SeriousM playlists aren't being processed properly

**Comment by bundit** [comment]
Playlists and profiles should be processed correctly now. Thanks & closed.

**Comment by SeriousM** [comment]
That works now flawlessly, thank you!
