### ISSUE TITLE
Expected version "11.12.x". Got "15.4.0" : Do I need to install older node?

### ISSUE THREAD

**Issue by anborg** [bundit/kord-app#19]
error music-pwa@1.0.0: The engine "node" is incompatible with this module. Expected version "11.12.x". Got "15.4.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by bundit** [comment]
@anborg I haven't taken the time to update it yet. At this time you can use NVM to set your node version to 11.12.0
