### ISSUE TITLE
Connect with YouTube is blocked

### ISSUE THREAD

**Issue by DerekPixel** [bundit/kord-app#20]
When I try to connect my YouTube account I get this message from Google:

![image](https://user-images.githubusercontent.com/63483631/103487759-98579880-4dbc-11eb-9bd8-c89b592ed8c4.png)

**Comment by bundit** [comment]
@DerekPixel Thanks for reporting this issue! A quick look at my google developer console tells me that we hit the user cap for unverified apps so I believe that's what is causing this issue. I will report back when I can have my application verified

**Comment by bundit** [comment]
@DerekPixel app is verified! Closing this issue
