### ISSUE TITLE
Youtube login with Google account is blocked

### ISSUE THREAD

**Issue by sepcol** [bundit/kord-app#25]
Trying to connect my YouTube account with my Google account gives me the following error

```
This app is blocked
This app tried to access sensitive info in your Google Account. To keep your account safe, Google blocked this access.
```

**Comment by bundit** [comment]
@sepcol 
Thanks for reporting. 

This is due to reaching user cap for unverified google apps. The application has been submitted so now we wait and see

**Comment by bundit** [comment]
@sepcol thanks for reporting. 

I have an issue open #20 for this at the moment so I'm closing this one for now.

**Comment by bundit** [comment]
@sepcol app is verified!

**Comment by sepcol** [comment]
Well done!
