### ISSUE TITLE
Connecting Spotify fails if user has no profile image

### ISSUE THREAD

**Issue by SanderRonde** [bundit/kord-app#30]
Connecting and refreshing your Spotify account fails when the user has no profile image, showing an error message saying "UNHANDLED ERRORUNDEFINED". I figured out that this was the cause by just pausing on exception and finding `json.images[0].url` in `mapJsonToProfile` throwin an error because `json.images` is an empty array in my case.

**Comment by bundit** [comment]
Fixed & close. Thanks
