### ISSUE TITLE
Seek bar is not functional on mobile

### ISSUE THREAD

**Issue by Eliasyoussef47** [bundit/kord-app#37]
You can't seek through a song. Not by clicking and not by dragging.

**Comment by bundit** [comment]
Sorry mobile is not currently supported. I am closing this for now.

I am considering a mobile app in the future, but no guarantees. Thanks for understanding

**Comment by Eliasyoussef47** [comment]
Do you accept help (pull requests)? I would've loved to help but I know nothing about the used technologies.

**Comment by bundit** [comment]
@Eliasyoussef47 if you'd like to submit a pull request I'd be happy to review and approve it after careful testing!

The knowledge necessary for making changes to the UI would be React and maybe Redux
