### ISSUE TITLE
Youtube video's play at a really low quality

### ISSUE THREAD

**Issue by shahzebgit** [bundit/kord-app#43]
If possible to set a default resolution for it or else totally remove it, because you don't want to watch something at lower/poor quality.

**Comment by bundit** [comment]
@shahzebgit Thanks for reporting. 

Currently, the youtube player defaults to adjusting to your bandwidth but I can look into creating a setting for selecting your preferred resolution although I'm afraid it will cause lag if your bandwidth is low in some cases. Or do you mean a setting to remove video entirely?

**Comment by shahzebgit** [comment]
> do you mean a setting to remove video entirely?

I mean if some people with lower bandwidth shouldn't see it entirely, because I'm listening to music after all.

> youtube player defaults to adjusting to your bandwidth

I have a decent connection and watch all video's on 1080p but on kord I think, it goes max 720p
