### ISSUE TITLE
Cannot click out of track-item_trackSettingsButton without clicking it again

### ISSUE THREAD

**Issue by andmarek** [bundit/kord-app#44]
Not sure if this is even an issue, but it made using the application *slightly* less fluid.  If this is too pedantic, I am sorry.

**Comment by bundit** [comment]
@andmarek thanks for reporting!

Just to make sure, do you mean the track drop down menu that has options like "add to playlist", "delete track", "add to queue" & "open in {source}"?

**Comment by bundit** [comment]
-fixed
