### ISSUE TITLE
Cant Search for titles / artists containing special characters

### ISSUE THREAD

**Issue by Austinpwrs** [bundit/kord-app#50]
**reproduction:**
OS: Win 10 Home,
Browser: MS Edge Version 88.0.705.81 (Offizielles Build) (64-Bit)
Search for "A$AP Rocky"

**what should happen:**
Every song containing the artist / title "A$AP Rocky" should be found

**what happened:**
Nothing was found, see screenshot

![image](https://user-images.githubusercontent.com/54191504/109834855-ea912a80-7c42-11eb-9f73-0d236aec8720.png)

**Comment by bundit** [comment]
Thanks & fixed
